### ISSUE TITLE
Separator Lines do not adapt to screen width

### ISSUE THREAD

**Issue by Bonhammer** [emacs-dashboard/emacs-dashboard#58] opened 2017-12-20 14:38 UTC
Hi, this is my first ever issue and I hope I'm not doing this wrong.

I just started using dashboard and noticed that the separator lines between the widgets do not adapt to the emacs window size at startup.
Thanks for providing the package in the first place.

**Comment by rakanalh** [comment] 2017-12-20 22:14
Hello @Bonhammer,

Glad you made your first contribution. Could you please provide a screenshot of how it looks? + Your emacs version and the version of emacs-dashboard you're using.

**Comment by Bonhammer** [comment] 2017-12-21 10:25
Hi Rakan,

I'm using Emacs version 25.1.90.1 (x86_64-w64-mingw32)
 of 2016-12-01
The dashboard version is 20170923.719

Here's a link to a screenshot: https://cloud.phil.hhu.de/index.php/s/6o5roZn6Xb4SOfa

Thanks for your help.

**Comment by SysConKonn** [comment] 2019-01-18 08:20
It seems that I have the same problem.
The lines can't adapt my window well.
![img](https://i.loli.net/2019/01/18/5c418bd178d7f.png)

**Comment by rakanalh** [comment] 2019-01-18 08:54
It works for me :tm: 

But the question is, you're saying "adapt"... so i am assuming that Emacs starts with a smaller size where the horizontal line goes all the way to the end and then you resize the window right?

**Comment by SysConKonn** [comment] 2019-01-18 09:11
It also didn't work right when emacs starts.

**Comment by Bonhammer** [comment] 2019-01-18 10:02
I have to report that the issue still persists for me.

However, there's a slight difference between the two cases: while @SysConKonn's separator lines seem __too short__ at Emacs startup, in my case the separator lines are __too long__ even though I maximize Emacs during startup.
I hope this observation is helpful.

**Comment by SysConKonn** [comment] 2019-01-18 10:23
The line with my [emacs config](https://github.com/SysConKonn/emacs.d) **works right** in my friend's computer, so I guess this problem was caused by fonts.

**Comment by JesusMtnez** [comment] 2019-03-01 07:57
@Bonhammer @SysConKonn does this issue persist?

**Comment by JesusMtnez** [comment] 2019-03-20 07:27
This doesn't seem to be a problem anymore. I'm closing this issue.

**Closed by JesusMtnez** 2019-03-20 07:27 UTC

**Comment by JacksonGariety** [comment] 2020-03-27 02:43
Still a problem.

**Comment by BBurkhardt** [comment] 2020-03-27 08:30
> Still a problem.
Yes, same here

> EDIT: but you can get rid of them with `(setq dashboard-page-separator "\n\n")`

Thanks alot for the suggestion! Much appreciated.

**Comment by BBurkhardt** [comment] 2020-03-27 08:46
> The line with my [emacs config](https://github.com/SysConKonn/emacs.d) **works right** in my friend's computer, so I guess this problem was caused by fonts.

Hm, thanks a bunch for the tip @SysConKonn, I'm using the following font settings:

```
(add-to-list 'default-frame-alist '(font . "Roboto Mono Light" ))
(set-face-attribute 'default nil :height 115)
```

If I comment out the first of the two lines, the separator lines behave as intended.
Is there anything wrong with that first line?
