### ISSUE TITLE
`b6c268f` causing daemon startup to stuck

### ISSUE THREAD

**Issue by itxprashant** [emacs-dashboard/emacs-dashboard#504] opened 2024-03-07 12:55 UTC
I bumped to the latest commit, and suddenly the daemon got stuck at startup with the default config. Then reverting back to `ed1a6a4` fixed that. Can't figure out what's causing this behaviour in `b6c268f`.

**Comment by jcs090218** [comment] 2024-03-07 21:13
I'm not able to reproduce this. 🤔 Are there any errors?

**Comment by ratson** [comment] 2024-03-08 06:48
@jcs090218 Try `emacs -nw -e kill-emacs`.
It is blocked by `face-attribute: Window system frame should be used`.

**Comment by jcs090218** [comment] 2024-03-08 08:08
I'm still not seeing this error. It safely executed on my side. 🤔

**Comment by SATYADAHAL** [comment] 2024-03-08 08:18
@jcs090218 i got error too. 
can you please tell me why on this [line](https://github.com/emacs-dashboard/emacs-dashboard/blob/c2d7d5f973d6d5d0dae507f208e4dabfea547561/dashboard-widgets.el#L743) we are not checking if there is graphical mode present or not? Shouldn't we check before image processing if graphical mode is present?

**Comment by SATYADAHAL** [comment] 2024-03-08 08:31
I thik I know  how this happened.  The function `image-multi-frame-p` does not work in terminal mode.
Code:
```lisp
(message "%s" (image-multi-frame-p (create-image "/home/spd/Desktop/back/bhasma.gif")))
```
Output:
```
message: Window system frame should be used  
```
And some one with dasboard config like this one will not have any problem.
```lisp
(setq dashboard-startup-banner                                                                                                                                                                         
      (if (display-graphic-p)                                                                                                                                                                         
        "/home/spd/Desktop/back/bhasma.webp"                                                                                                                                                                     
        1)) ; Set the desired integer value for terminal mode                                           
```
I think you and I didnot get this error due to config like this. But people using image only in dashboard config got the error.
We need to check if graphical mode is present before executing this function.

**Comment by SATYADAHAL** [comment] 2024-03-08 08:34
@jcs090218  Check if you have similar config and if so check if you get the error.

**Comment by jcs090218** [comment] 2024-03-08 08:57
Should fixed in fbf54b12d8aa6b9853d32ee9b635004ad6bc0e41.

**Comment by jcs090218** [comment] 2024-03-08 08:57
> can you please tell me why on this [line](https://github.com/emacs-dashboard/emacs-dashboard/blob/c2d7d5f973d6d5d0dae507f208e4dabfea547561/dashboard-widgets.el#L743) we are not checking if there is graphical mode present or not? Shouldn't we check before image processing if graphical mode is present?

Some terminals support displaying images.

**Closed by jcs090218** 2024-03-08 08:57 UTC
Labels: question, daemon

**Comment by itxprashant** [comment] 2024-03-08 09:35
Thanks guys!
