### ISSUE TITLE
Mouse click errors

### ISSUE THREAD

**Issue by paxperscientiam** [emacs-dashboard/emacs-dashboard#184] opened 2019-08-22 14:50 UTC
Hello, I'm trying out emacs-dashboard. It works well in Emacs for Mac, but fails in dumb terminals. Basically, it seems like mouse clicking is broken.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7539871/63524854-b6c03b00-c4ca-11e9-9020-675b67bdf96d.gif)

**Comment by jcs090218** [comment] 2020-01-10 08:50
What terminal are you using? Just the default terminal from Mac? Might need more information on this.

**Comment by paxperscientiam** [comment] 2020-01-11 04:40
@jcs090218 iTerm2 on macos

**Comment by JesusMtnez** [comment] 2020-01-20 11:08
I think the problem is not related to `emacs-dashboard`. I do not use MacOS, so I could not assist you here.

Did you find a way to fix it @paxperscientiam ?

**Comment by jcs090218** [comment] 2020-10-18 14:31
Yeah, I cannot reproduce this on my Windows machine. I agree with @JesusMtnez that this may cause by the terminal you are using. 😕

**Comment by zcaudate** [comment] 2020-12-16 02:30
I'm having the same issue with the letters. Also on macOS.

**Comment by zcaudate** [comment] 2020-12-16 02:30
I've used Terminal.app, Term2 and Alacritty and they all do the same thing. I'm wondering if there was a way to disable the mouse

**Comment by zcaudate** [comment] 2020-12-16 02:41
I figured out how to disable it:

```
(define-key dashboard-mode-map [down-mouse-1] nil)
```

a work around is to click using the mouse and press RET on the file you want.

**Comment by paxperscientiam** [comment] 2020-12-28 04:23
@zcaudate  that indeed works. Just submitted PR #282 using your find.

**Comment by jcs090218** [comment] 2020-12-28 06:01
Do we even need this line in the first place? I think without this line the dashboard works functionally without causing issue.

https://github.com/emacs-dashboard/emacs-dashboard/blob/ef51ad205c6f21e80cb1e4b2ab2d0547675ea206/dashboard.el#L44

**Comment by paxperscientiam** [comment] 2020-12-30 02:21
My assumption is "yes." If not explicitly set in mode-map, we can't be sure what will be bound to it ... though perhaps it's likely just to be the default value.

**Comment by jcs090218** [comment] 2020-12-31 17:00
> My assumption is "yes." If not explicitly set in mode-map, we can't be sure what will be bound to it ... though perhaps it's likely just to be the default value.

I don't think we need this since `widget-button` should act as button object in Emacs. Unless it bounds to something else that mouse no longer do it usual behaviour.

> EDIT: Just to add, I did test removing line 44 and emacs-dashboard does work as expected in dumb terminal and graphical terminal.

Okay, I have a PR #283 for temporary solution!

**Comment by jcs090218** [comment] 2021-01-01 06:39
I assumed this issue is fixed! Thanks! ;)

**Comment by jcs090218** [comment] 2021-01-02 16:41
The previous #283 solution isn't perfect, reopening this issue. 😕

**Comment by paxperscientiam** [comment] 2021-01-02 16:52
My solution DOES work, but we could go a step further and make it so that clicking the filename opens a file visiting buffer like in spacemacs. Spacemacs looks like they've augmented emacs-dashboard in someway.

**Comment by jcs090218** [comment] 2021-01-02 16:56
I know your solution here.

```el
(if (display-graphic-p)
    (define-key dashboard-mode-map [down-mouse-1] 'widget-button-click)
  (define-key dashboard-mode-map [down-mouse-1] nil))
```

But this doesn't work on my machine. 😕 Can you test using `mouse-1` instead of `down-mouse-click`? I am guessing `down-mouse-1` isn't the right keymap to use.

**Comment by paxperscientiam** [comment] 2021-01-02 17:01
> But this doesn't work on my machine

Oh no, sorry. didn't realize. I will give your snippet a shot.

**Comment by paxperscientiam** [comment] 2021-01-02 17:08
Works for me! You'll use your own PR?

**Comment by jcs090218** [comment] 2021-01-02 17:13
> Works for me! You'll use your own PR?

Great! I never thought the solution would be that simple. Thank god!

I have opened the PR #285 but I would need to wait for @JesusMtnez to confirm! If you want, you can open another PR so I can merge it immediately!

**Comment by jcs090218** [comment] 2021-01-02 17:22
Cool, @JesusMtnez has approved PR. Thanks for everyone's participation! Close this issue now!

@paxperscientiam Feel free to reopen this issue if this issue remains!

**Closed by jcs090218** 2021-01-02 17:22 UTC
Labels: question
