### ISSUE TITLE
Resize hook affects all frames

### ISSUE THREAD

**Issue by mtreca** [emacs-dashboard/emacs-dashboard#197] opened 2019-11-11 12:18 UTC
When using dashboard and emacsclient, resizing an emacs frame triggers the resize hook and all frames, making some frames uncentered.

Before:

![2019-11-11-131543_1920x1080_scrot](https://user-images.githubusercontent.com/16440823/68586781-b0b47780-0485-11ea-9da0-b919fa865afc.png)

After:

![2019-11-11-131552_1920x1080_scrot](https://user-images.githubusercontent.com/16440823/68586747-a0040180-0485-11ea-9730-be6fb22563e3.png)

**Comment by jcs090218** [comment] 2020-02-14 02:14
Just to confirm, you are talking about the image aren't centered in the second image? Is the correct? Thanks!

**Comment by vxid** [comment] 2020-02-14 08:33
@jcs090218 Yes exactly.

**Comment by jcs090218** [comment] 2020-10-18 14:15
Sorry for the late reply!

I can reproduce issue. I think the solution is to loop through all frames in order to do re-centering execution correctly.

**Comment by jcs090218** [comment] 2020-10-18 14:29
Oh, wait. This is actually quite tricky... 

Since we only have one `dashboard buffer` but we have two frames with different sizes. I don't know if this is possible to fix. May need suggestion on this. I will mark this as `help wanted` label for now.

**Comment by mtreca** [comment] 2020-10-18 18:13
Hi again, no problems for the reply!

I thought about it in the meantime and reached the same conclusion: if two Emacs frames of different width are displaying the dashboard at the same time, there is no way of displaying both dashboards correctly at the same time. The only edge cases that could be fixed is if the frames are on two different workspaces (depending on your window manager) and there is a reliable way of telling whether an Emacs frame is not on the currently active workspace. But I don't think this is possible or worth pursuing.

**Comment by jcs090218** [comment] 2020-10-19 07:41
Yeah, I totally agree with you. I may mark this with `won't fix` label; then until we have a good solution for this issue.

**Closed** 2022-11-16 11:55 UTC
Labels: bug, help wanted
