### ISSUE TITLE
dashboard buffer is not created

### ISSUE THREAD

**Issue by joncarr** [emacs-dashboard/emacs-dashboard#199] opened 2019-11-23 13:02 UTC
When starting Emacs the dashboard buffer is never created. I receive an error telling me that my initial buffer choice is not a live buffer. The buffer I am looking for as the initial buffer is `*dashboard*`.

Here is my use package configuration for the package:
```
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '(
                (recents . 5)
                (projects . 10)
                ))
    (setq dashboard-banner-logo-title "")
    (setq dashboard-startup-banner "~/.emacs.d/img/dashLogo.png"))
    (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
```
This worked great for the longest time then it just seemed to stop opening the dashboard one day. I receive no other errors and when I look at my buffer list, a dashboard buffer is not listed.

**Comment by utraz** [comment] 2019-12-03 13:57
I'm having the same issue, It just stopped showing up.

**Comment by hakantunc** [comment] 2019-12-13 01:55
Can you try `:init` instead of `:config` for the function call `dashboard-setup-startup-hook`?

```
:init
(dashboard-setup-startup-hook)
```

**Comment by utraz** [comment] 2019-12-13 17:38
Still nothing

**Comment by joncarr** [comment] 2019-12-17 02:34
> Can you try `:init` instead of `:config` for the function call `dashboard-setup-startup-hook`?
> 
> ```
> :init
> (dashboard-setup-startup-hook)
> ```

This worked for me. Thanks!

**Comment by jcs090218** [comment] 2020-02-14 02:12
That is strange.. I reckon somehow the `dashbaord` itself is `defer` loading and that is why `dashboard` wouldn't show up in the first place. 

Anyway, if the problem is resolved. We should close this issue! Thank you!

Ping @joncarr @utraz

**Closed** 2020-02-14 16:19 UTC
