### ISSUE TITLE
No icons in dashboard on Windows

### ISSUE THREAD

**Issue by seagle0128** [emacs-dashboard/emacs-dashboard#471] opened 2023-08-10 11:25 UTC
I am using Emacs 28.2/29.1 on Windows 11, with the latest dashboard package. There is no icon for files and sections on Windows, but all are fine on macOS/Ubuntu/WSL, even in terminals. I tried emacs -Q, and the issue still there.

My configurations are [here](https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-dashboard.el).

The screenshot is below.

![image](https://github.com/emacs-dashboard/emacs-dashboard/assets/140797/8e3efe49-81fc-4790-b4a2-15994ddbf783)

**Comment by jcs090218** [comment] 2023-08-10 16:42
I think it's because of this, see https://github.com/emacs-dashboard/emacs-dashboard/pull/467. 🤔 I'm still trying to investigate the issue, but I haven't figured out a better solution.

**Comment by seagle0128** [comment] 2023-08-11 02:40
If I override `dashboard-replace-displayable` with below function, it works well.

```elisp
(defun dashboard-replace-displayable (str &optional rep)
  str)
```

**Comment by jcs090218** [comment] 2023-08-11 03:21
> The function seems not necessary. The wired thing is the issue only exists on Windows.

It does the job when characters are undisplayable. The issue is that the result is inconsistent on different platforms/terminals. 🤔 That's the problem we need to investigate! 😓 Sorry for the inconvenience!

**Comment by seagle0128** [comment] 2023-08-11 04:09
Gocha. It's not necessary for nerd-icons IMO. It's useful for `all-the-icons`, but `display-graphic-p` should solve it.

**Comment by jcs090218** [comment] 2023-08-11 04:46
> Gocha. It's not necessary for nerd-icons IMO. It's useful for all-the-icons, but display-graphic-p should solve it.

It happens in both terminal/graphical Emacs; therefore, I haven't merged PR #467. I really hope I have the knowledge regarding this issue. Unfortunately, I do not. 😓

**Comment by seagle0128** [comment] 2023-08-11 06:03
It seems that `char-displayable-p` is not suitable for icons.

**Comment by jcs090218** [comment] 2023-08-11 19:39
> It seems that `char-displayable-p` is not suitable for icons.

That's what I need to investigate because it works on my Windows 11 (graphical & terminal) but not yours and a few other people's. 🤔

**Comment by jordan4ibanez** [comment] 2023-08-30 17:47
I don't know if I'm just a horrible emacs noobert but I can't get this to work either :(

**Comment by seagle0128** [comment] 2023-08-31 02:26
@jordan4ibanez  My workaround

```elisp
(advice-add #'dashboard-replace-displayable :override #'identity)
```

**Comment by jordan4ibanez** [comment] 2023-09-01 20:24
> 

I got it working, I just have no idea how :P

**Comment by seagle0128** [comment] 2024-03-22 03:16
The issue appears again.

**Comment by jcs090218** [comment] 2024-03-22 03:47
We haven't changed anything regarding the icons. 🤔 

cc @DevelopmentCool2449 In case you know anything.

**Comment by DevelopmentCool2449** [comment] 2024-03-22 04:42
> We haven't changed anything regarding the icons. 🤔
>
> cc @DevelopmentCool2449 <https://github.com/DevelopmentCool2449> In case
> you know anything.
>
I'll try to find the problem, when i have a solution i will make a PR that
can fix this issue.

since i'm using windows i didn't have an issue like this, when melpa lets
me upgrade to lastest dashboard version i will start on working a solution

>

**Comment by DevelopmentCool2449** [comment] 2024-03-22 16:16
I'm not sure why this issue happens in my windows setup nerd icons works fine, 
i can't replicate it.

@seagle0128 can you share what do you have in your dashboard or nerd icons setup?

**Comment by DevelopmentCool2449** [comment] 2024-03-22 21:04
It seems to be a problem with your windows, i used your configuration in my windows 10 and nerd icons works fine.

![Screenshot_1](https://github.com/emacs-dashboard/emacs-dashboard/assets/163072436/f146a962-54a8-4b57-b427-5b5be7c704ff)

I don't think it could be a issue with dashboard, but at the moment I don't know any solution 😓.

**Comment by seagle0128** [comment] 2024-03-25 09:25
The root cause is `dashboard-replace-displayable` returns `""` somehow. I think not only me encountered this issue.

**Comment by DevelopmentCool2449** [comment] 2024-03-25 16:42
Can you eval these snippets and and tell what do you get?

```(insert (dashboard-replace-displayable
         (apply #'nerd-icons-icon-for-file "file.el" :height '(2))))

(char-displayable-p (string-to-char (apply #'nerd-icons-icon-for-file "file.el" :height '(2))))
```

**Comment by seagle0128** [comment] 2024-03-26 02:10
Sure.

```elisp
;;#1 => nil
(insert (dashboard-replace-displayable
         (apply #'nerd-icons-icon-for-file "file.el" :height '(2))))

;;#2 => nil
(char-displayable-p (string-to-char (apply #'nerd-icons-icon-for-file "file.el" :height '(2))))

;;#3 => nil
(char-displayable-p (string-to-char (nerd-icons-icon-for-file "file.el" :height 2)))

;;#4 => t
(stringp (apply #'nerd-icons-icon-for-file "file.el" :height '(2)))
```

**Comment by DevelopmentCool2449** [comment] 2024-03-26 02:48
Then isn't a dashboard problem as i see.

`apply` works well but `char-displayable-p` is failing.

can you do another test?
```elisp
(string-to-char (nerd-icons-icon-for-file "file.el" :height 2))

(string-to-char (apply #'nerd-icons-icon-for-file "file.el" :height '(2)))
```

**Comment by seagle0128** [comment] 2024-03-26 06:32
The results are same: 58930.

```elisp
;;#1
(string-to-char (nerd-icons-icon-for-file "file.el" :height 2))

;;#2
(string-to-char (apply #'nerd-icons-icon-for-file "file.el" :height '(2)))
```

**Comment by DevelopmentCool2449** [comment] 2024-03-26 21:54
I could reproduce the issue, it is due `char-displayable-p` is only checking if icon is displayable on current frame font, changing font to anyone that is not from nerd-fonts fonts makes this issue, i've open a PR https://github.com/emacs-dashboard/emacs-dashboard/pull/521 that may fix this.

**Comment by jcs090218** [comment] 2024-03-26 22:44
I am still bewildered since I am also on Windows 11, but I cannot reproduce this issue...

**Comment by DevelopmentCool2449** [comment] 2024-03-26 22:50
> I am still bewildered since I am also on Windows 11, but I cannot reproduce this issue...

Try changing your current frame font to anyone that don't have nerd-icons glyph and setting `nerd-icons-font-family` to `"Symbols Nerd Font Mono"` (make sure you have that font installed)

**Comment by jcs090218** [comment] 2024-03-26 23:12
> Try changing your current frame font to anyone that don't have nerd-icons glyph like Arial or Consolas and setting nerd-icons-font-family to "Symbols Nerd Font Mono" (make sure you have that font installed)

It still works for me. 🤔 

| Consolas | Arial  |
|---|---|
| ![2024-03-26 16 11 38](https://github.com/emacs-dashboard/emacs-dashboard/assets/8685505/eb661e33-2004-4c80-87ee-c6cf979bba3c) | ![2024-03-26 16 11 56](https://github.com/emacs-dashboard/emacs-dashboard/assets/8685505/176ef218-1327-4e7f-a733-b4a2ccdac07f) |

**Comment by DevelopmentCool2449** [comment] 2024-03-26 23:25
Try with `emacs -Q` and only using `nerd-icons` with a basic dashboard setup
or disabling `use-ttf`

**Comment by seagle0128** [comment] 2024-04-01 05:57
I think you guys got the root cause?

**Comment by jcs090218** [comment] 2024-04-01 06:29
This is the reason why I can't reproduce this issue:

https://github.com/jcs-emacs/jcs-emacs/blob/master/early-init.el#L60

Adding this line can resolve this issue:

```elisp
(set-language-environment "UTF-8")
```

**Comment by seagle0128** [comment] 2024-04-01 07:39
> ```emacs-lisp
> (set-language-environment "UTF-8")
> ```

This doesn't work. Only this works for me: `(advice-add #'dashboard-replace-displayable :override #'identity)`.
BTW, in my config, I was using `(prefer-coding-system 'utf-8)`.

**Comment by jcs090218** [comment] 2024-04-01 07:53
Hmmm... `(set-language-environment "UTF-8")` works for me. I tried it in `emacs -q` on Windows 11.

```elisp
(set-language-environment "UTF-8")  ; char-displayable-p returns 'unicode
(set-language-environment "English")  ; char-displayable-p returns nil
```

🤔

**Comment by DevelopmentCool2449** [comment] 2024-04-01 20:02
Apparently `(prefer-coding-system 'utf-8)` and `(set-language-environment "UTF-8")` only works well in `early-init.el`.

**Comment by seagle0128** [comment] 2024-04-03 03:50
> Apparently `(prefer-coding-system 'utf-8)` and `(set-language-environment "UTF-8")` only works well in `early-init.el`.

@DevelopmentCool2449 You are right! But, the icons can be displayed even though the coding system is not UTF-8.   Why does ``dashboard-replace-displayable` depend on UTF-8?

**Comment by DevelopmentCool2449** [comment] 2024-04-05 02:54
> > Apparently `(prefer-coding-system 'utf-8)` and `(set-language-environment "UTF-8")` only works well in `early-init.el`.
> 
> @DevelopmentCool2449 You are right! But, the icons can be displayed even though the coding system is not UTF-8.

I need to test it, do you know how to reproduce that.

> Does ``dashboard-replace-displayable` depend on UTF-8?

I'm unsure about that, `dashboard-replace-displayable`, AFAIK it uses `char-displayable-p`
for ensure that the icon is always available/displayable which i think it needs UTF-8 for 
display nerd-icons since it uses a custom char set.

**Comment by jcs090218** [comment] 2024-04-07 00:06
> I'm unsure about that, dashboard-replace-displayable, AFAIK it uses char-displayable-p
for ensure that the icon is always available/displayable which i think it needs UTF-8 for
display nerd-icons since it uses a custom char set.

This is correct. :)

**Closed** 2024-04-07 00:13 UTC
Labels: bug

**Comment by seagle0128** [comment] 2024-04-07 02:31
I moved `(prefer-coding-system 'utf-8)` to `early-init.el`. All icons are displayed correctly in both macOS and Linux, without setting the coding system specifically.

**Comment by rabiahmad** [comment] 2024-08-24 16:22
> Hmmm... `(set-language-environment "UTF-8")` works for me. I tried it in `emacs -q` on Windows 11.
> 
> ```emacs-lisp
> (set-language-environment "UTF-8")  ; char-displayable-p returns 'unicode
> (set-language-environment "English")  ; char-displayable-p returns nil
> ```
> 
> 🤔

This worked for me, but only when I added these lines into early-init.el. I am on Windows 11. Icons are now showing :)

**Comment by sebastian-j-ibanez** [comment] 2025-06-24 20:53
I had the same issue on Windows 11.

I can confirm this still works (for anyone else who stumbles on this ticket while debugging their config).
