### ISSUE TITLE
dashboard-insert-image-banner: Window system frame should be used

### ISSUE THREAD

**Issue by junyu-wu** [emacs-dashboard/emacs-dashboard#250] opened 2020-10-30 07:55 UTC
tty: dashboard version: 20201029.1110
      error: dashboard-insert-image-banner: Window system frame should be used

      dashboard version: 20200306.1344 
      successful

**Comment by jcs090218** [comment] 2020-10-30 08:04
I think the issue is cause after #246. 

Try specify `dashboard-startup-banner` only when `(display-graphic-p)` is true.

```el
(setq dashboard-startup-banner (when (display-graphic-p) "path/to/img.png")
```

**Comment by junyu-wu** [comment] 2020-10-30 08:29
If you just set dashboard-startup-banner to false, the text banner cannot be displayed.
I checked `dashboard-choose-banner` func, modify like this 

``` emacs-lisp
(setq dashboard-startup-banner (if (display-graphic-p) "path.png") 't))
```

the text banner is successfully displayed and without an error

**Comment by jcs090218** [comment] 2020-10-30 08:35
I have made a PR #251. I think the fix should resolve the compatible issue from the previous version.

**Comment by jcs090218** [comment] 2020-10-30 08:57
The PR #251 is merged! Feel free to reopen this if the issue remains. Thank you!

**Closed** 2020-10-30 08:56 UTC
Labels: question
